name: SiegeSafeBaseShield
version: '1.0-SNAPSHOT'
main: me.mika.midomikasiegesafebaseshield.SiegeSafeBaseShield
api-version: '1.19'
commands:
#  taskstop:
#    description: stop task
  SSBS:
    description: save, delete, list and select commands